name: No duplication

on: [push, pull_request]

jobs:
  nodups:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: Check duplications
      run: jscpd . --min-lines 9 --min-tokens 85 --threshold 0
